# Generated by Django 5.2.9 on 2025-12-22 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "receipts",
            "0002_purchasecluster_receiptitem_brand_receiptitem_form_and_more",
        ),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="purchase",
            name="receipts_pu_purchas_a3651b_idx",
        ),
        migrations.RemoveIndex(
            model_name="purchase",
            name="receipts_pu_merchan_629134_idx",
        ),
        migrations.RemoveField(
            model_name="purchase",
            name="merchant",
        ),
        migrations.RemoveField(
            model_name="purchase",
            name="purchased_at",
        ),
        migrations.RemoveField(
            model_name="receiptitem",
            name="brand",
        ),
        migrations.RemoveField(
            model_name="receiptitem",
            name="form",
        ),
        migrations.RemoveField(
            model_name="receiptitem",
            name="pack_size_unit",
        ),
        migrations.RemoveField(
            model_name="receiptitem",
            name="variety",
        ),
    ]
