# Generated by Django 5.2.9 on 2025-12-22 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("receipts", "0004_remove_receiptitem_pack_size_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="receiptitem",
            name="pack_size",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="receiptitem",
            name="unit_type",
            field=models.CharField(blank=True, default="", max_length=32),
        ),
    ]
