# Generated by Django 5.2.9 on 2025-12-22 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("receipts", "0005_receiptitem_pack_size_receiptitem_unit_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="receiptitem",
            name="unit_type",
            field=models.CharField(blank=True, default="", max_length=32, null=True),
        ),
    ]
